‚ùå ERROR: (psycopg2.errors.InvalidSchemaName) schema "np" does not exist LINE 1: ..., 4.25, 5.0, 4.25, -5, 62.25, 5.935637663885578, np.float64... ^ [SQL: INSERT INTO backtest_runs (user_id, strategy_name, symbol, timeframe, initial_balance, trade_amount, payout_percent, trade_duration, start_time, end_time, final_balance, total_trades, winning_trades, losing_trades, draw_trades, win_rate, profit_factor, net_profit, return_percent, total_profit, total_loss, gross_profit, gross_loss, average_win, average_loss, largest_win, largest_loss, max_drawdown, max_drawdown_percent, sharpe_ratio, max_consecutive_wins, max_consecutive_losses, created_at) VALUES (%(user_id)s, %(strategy_name)s, %(symbol)s, %(timeframe)s, %(initial_balance)s, %(trade_amount)s, %(payout_percent)s, %(trade_duration)s, %(start_time)s, %(end_time)s, %(final_balance)s, %(total_trades)s, %(winning_trades)s, %(losing_trades)s, %(draw_trades)s, %(win_rate)s, %(profit_factor)s, %(net_profit)s, %(return_percent)s, %(total_profit)s, %(total_loss)s, %(gross_profit)s, %(gross_loss)s, %(average_win)s, %(average_loss)s, %(largest_win)s, %(largest_loss)s, %(max_drawdown)s, %(max_drawdown_percent)s, %(sharpe_ratio)s, %(max_consecutive_wins)s, %(max_consecutive_losses)s, %(created_at)s) RETURNING backtest_runs.id] [parameters: {'user_id': 'c184e7d6-8fb2-484e-b7a0-40386f79ac4f', 'strategy_name': 'RSI Oversold/Overbought', 'symbol': 'XAUUSD-OTC', 'timeframe': 'M5', 'initial_balance': 1000, 'trade_amount': 5, 'payout_percent': 85, 'trade_duration': 1, 'start_time': 1758772800, 'end_time': 1759751400, 'final_balance': 1004.25, 'total_trades': 154, 'winning_trades': 81, 'losing_trades': 68, 'draw_trades': 5, 'win_rate': 52.5974025974026, 'profit_factor': 1.0125, 'net_profit': 4.25, 'return_percent': 0.42500000000000004, 'total_profit': 4.25, 'total_loss': 0.0, 'gross_profit': 344.25, 'gross_loss': -340.0, 'average_win': 4.25, 'average_loss': 5.0, 'largest_win': 4.25, 'largest_loss': -5, 'max_drawdown': 62.25, 'max_drawdown_percent': 5.935637663885578, 'sharpe_ratio': np.float64(0.133169709988598), 'max_consecutive_wins': 6, 'max_consecutive_losses': 7, 'created_at': datetime.datetime(2025, 10, 6, 13, 18, 34, 640478)}] (Background on this error at: https://sqlalche.me/e/20/f405)